### Site Settings ###
title               : Yu Qin
description         : >-
#                      "Wit Beyond Measure is Man's Greatest Treasure"                 
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : GeminiLn/GeminiLn.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects) 

### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/projects.html


### Author Info ###
author:
  name              : Yu Qin
#  image             : https://i.loli.net/2020/02/24/bTmhSPlg4VND95k.jpg
#  image             : https://s2.loli.net/2023/03/29/gETHvNrLGJu1Rk3.jpg
  image             : https://s2.loli.net/2025/08/24/fib4k7zmglAtD6Y.jpg
# behance           : your_username
# dribbble          : your_username
  email             : yu.qin@eccles.utah.edu
# facebook          : your_username
  github            : GeminiLn
# gitlab            : your_username
# instagram         : your_username
  linkedin          : yu7qin
# medium            : your_username
# soundcloud        : your_username
  spotify           : 31vfoy5lq4a3js3ytophufxzrfnm
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
